<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Property;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('properties')->insert([
            [
                'property_id' => 'PR001',
                'owner_id' => 'OWN001',
                'branch_id' => 'BR001',
                'staff_id' => 'ST0001',
                'street' => '221B Baker Street',
                'area' => 'Marylebone',
                'city' => 'London',
                'postcode' => 'NW1 6XE',
                'type' => 'apartment',
                'rooms' => 3,
                'monthly_rent' => 112000.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'property_id' => 'PR002',
                'owner_id' => 'OWN002',
                'branch_id' => 'BR001',
                'staff_id' => 'ST0002',
                'street' => '42 Wallaby Way',
                'area' => 'Sydney CBD',
                'city' => 'Sydney',
                'postcode' => '2000',
                'type' => 'studio',
                'rooms' => 1,
                'monthly_rent' => 29000.00,
                'status' => 'rented',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'property_id' => 'PR003',
                'owner_id' => 'OWN001',
                'branch_id' => 'BR002',
                'staff_id' => 'ST0003',
                'street' => '742 Evergreen Terrace',
                'area' => 'Springfield',
                'city' => 'Oregon',
                'postcode' => '97477',
                'type' => 'house',
                'rooms' => 4,
                'monthly_rent' => 50000.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'property_id' => 'PR004',
                'owner_id' => 'OWN003',
                'branch_id' => 'BR003',
                'staff_id' => null, // Testing your nullable staff constraint
                'street' => '12 Grimmauld Place',
                'area' => 'Islington',
                'city' => 'London',
                'postcode' => 'N1 9AA',
                'type' => 'house',
                'rooms' => 5,
                'monthly_rent' => 90000.00,
                'status' => 'maintenance',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'property_id' => 'PR005',
                'owner_id' => 'OWN004',
                'branch_id' => 'BR001',
                'staff_id' => 'ST0001',
                'street' => '32 Windsor Gardens',
                'area' => 'Notting Hill',
                'city' => 'London',
                'postcode' => 'W11 2JG',
                'type' => 'apartment',
                'rooms' => 2,
                'monthly_rent' => 21000.00,
                'status' => 'reserved',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'property_id' => 'PR006',
                'owner_id' => 'OWN002',
                'branch_id' => 'BR002',
                'staff_id' => 'ST0004',
                'street' => '124 Conch Street',
                'area' => 'Bikini Bottom',
                'city' => 'Pacific',
                'postcode' => '00001',
                'type' => 'condo',
                'rooms' => 2,
                'monthly_rent' => 30000.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'property_id' => 'PR007',
                'owner_id' => 'OWN005',
                'branch_id' => 'BR003',
                'staff_id' => 'ST0005',
                'street' => '1600 Pennsylvania Ave',
                'area' => 'Downtown',
                'city' => 'Washington DC',
                'postcode' => '20500',
                'type' => 'condo',
                'rooms' => 6,
                'monthly_rent' => 8500.00,
                'status' => 'rented',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'property_id' => 'PR008',
                'owner_id' => 'OWN003',
                'branch_id' => 'BR001',
                'staff_id' => 'ST0002',
                'street' => '56B Abbey Road',
                'area' => 'St Johns Wood',
                'city' => 'London',
                'postcode' => 'NW8 9AY',
                'type' => 'apartment',
                'rooms' => 3,
                'monthly_rent' => 28000.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'property_id' => 'PR009',
                'owner_id' => 'OWN005',
                'branch_id' => 'BR003',
                'staff_id' => 'ST0006',
                'street' => '710 Ashbury Street',
                'area' => 'Haight-Ashbury',
                'city' => 'San Francisco',
                'postcode' => '94117',
                'type' => 'studio',
                'rooms' => 4,
                'monthly_rent' => 100000.00,
                'status' => 'maintenance',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'property_id' => 'PR010',
                'owner_id' => 'OWN004',
                'branch_id' => 'BR002',
                'staff_id' => null,
                'street' => '21 Jump Street',
                'area' => 'Metro',
                'city' => 'Los Angeles',
                'postcode' => '90001',
                'type' => 'condo',
                'rooms' => 1,
                'monthly_rent' => 39000.00,
                'status' => 'available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}